global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'sscm-backend'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['backend:8080']
        labels:
          environment: prod
