apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    editable: true
  - name: CloudWatch
    type: cloudwatch
    access: proxy
    uid: cloudwatch
    jsonData:
      authType: default
      defaultRegion: ap-northeast-2
    editable: true
